# Launch bot
name: Downloads Count

on:
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/github-script@v6
    - uses: actions/setup-node@v1
      with:
        node-version: '16'
    - name: Test hello world
      run: |
        echo "Hello world"