# Launch bot
name: Downloads Count

on:
  workflow_dispatch:

jobs:
  get-all-releases-count:
    runs-on: ubuntu-latest

    outputs:
      myOutput: ${{ steps.process-downloads.outputs.myOutput }}
      myOutput2: ${{ steps.process-downloads.outputs.myOutput2 }}
      totalMac: ${{ steps.process-downloads.outputs.totalMac }}
      totalWin: ${{ steps.process-downloads.outputs.totalWin }}
      totalLinux: ${{ steps.process-downloads.outputs.totalLinux }}
      totalDownloads: ${{ steps.process-downloads.outputs.totalDownloads }}

    steps:
      - uses: actions/github-script@v6
        id: process-downloads
        with:
          script: |
            const resp = await github.paginate('GET /repos/{owner}/{repo}/releases{?per_page,page}', {
                owner: 'containers',
                repo: 'podman-desktop',
                per_page: 100
            }, (response) => response.data.map(({ tag_name, assets }) => ({ tag_name, assets })));

            const releases = resp;

            // Create a new json array which keeps tag_name and assets from result
            //const releases = resp.data.map(({ tag_name, assets }) => ({ tag_name, assets }))

            // Keep only tag_name and asset.name and asset.download_count from releases
            releases.forEach((release) => { release.assets = release.assets.map(({ name, download_count }) => ({ name, download_count })) })

            let totalMac = 0;
            let totalWin = 0;
            let totalLinux = 0;

            // count the total number of downloads for each release for mac,windows,linux assests
            releases.forEach((release) => { 
                release.assets = release.assets.filter((asset) => { 
                    if (asset.name.endsWith(".dmg") || (asset.name.endsWith("arm64.zip") || asset.name.endsWith("x64.zip") || asset.name.endsWith("universal.zip")) ){
                        totalMac += asset.download_count;
                    } else if (asset.name.endsWith(".exe")){
                        totalWin += asset.download_count;
                    } else if (asset.name.endsWith(".tar.gz") || asset.name.endsWith(".flatpak")){
                        totalLinux+=asset.download_count;
                    }
                })
            })

            let totalDownloads = totalMac + totalWin + totalLinux;

            // Export results as outputs
            console.log(`::set-output name=totalMac::${totalMac}`);
            console.log(`::set-output name=totalWin::${totalWin}`);
            console.log(`::set-output name=totalLinux::${totalLinux}`);
            console.log(`::set-output name=totalDownloads::${totalDownloads}`);

            //test using environment variable
            console.log(`ACTION_STATE=yellow` >> $GITHUB_ENV);

            const actionState = process.env.ACTION_STATE;
            console.log(`The action state is: ${actionState}`);
            
            const fs = require('fs');
            fs.appendFileSync(process.env.GITHUB_ENV, `ACTION_STATE3=blue\n`);

            const actionState3 = process.env.ACTION_STATE3;
            console.log(`3333The action state is: ${actionState3}`);

          
      - name: send-event-4
        run: |
            echo "${{ env.action_state }}"
            curl https://api.segment.io/v1/track \
            -X POST \
            -H 'Content-Type: application/json' \
            -d '{
              "userId": "gh-action",
              "event": "download-count",
               "properties": {
                "mac": "${{ steps.process-downloads.outputs.totalMac }}",
                "windows": "${{ steps.process-downloads.outputs.totalWin }}",
                "linux": "${{ steps.process-downloads.outputs.totalLinux }}",
                "total": "${{ steps.process-downloads.outputs.totalDownloads }}"
              }
            }' \
            -u Mhl7GXADk5M1vG6r9FXztbCqWRQY8XPy
